---
title: "Ejercicios de repaso"
author: "Lucas Fehlau Arbulu"
date: "31-05-2022"
output: 
    html_document:
        toc: true
        number_sections: false
        toc_float: true
---
```{r setup, include=FALSE}
# knitr::opts_knit$set(global.device = TRUE)
```
# Ejecicio 1
```{r}
set.seed(1)
y <- rchisq(n = 50, df = 30)
x <- rnorm(n = 50, mean = 30, sd = 5)
```
### 1
```{r}
mean(y)
sd(y)
quantile(y, probs = c(0.25, 0.5, 0.75))
```
### 2
```{r}
hist(y, freq = FALSE, main = "Muestra de Chi cuadrado", ylim = c(0, max(dnorm(x, mean = mean(x), sd = sd(x)))))

lines(density(y))
curve(dnorm(x, mean = mean(y), sd = sd(y)), add = TRUE)
```

### 4
```{r}
qqnorm(y)
qqline(y)
```
Observamos que $y$ se asemeja a la normal, salvo en la cola derecha.

### 5
```{r}
boxplot(y)
```

### 6
```{r}
boxplot(x, y, names = c("x", "y"))
```

### 7, 8
```{r}
plot(x, y)
modelo <- lm(y ~ x)
abline(modelo)
```

# Ejecicio 2
### 1
```{r}
apuesta <- function(dados = 4) {
    muestra <- sample(1:6, dados, replace = TRUE)
    any(muestra == 6)
    # 6 %in% muestra # alternativa
}
```
### 2
```{r}
nsim <- 10000
set.seed(1)
x <- replicate(nsim, apuesta())
# versión anterior:
# x <- rep(4, nsim)
# x <- sapply(x, apuesta)
aprox <- mean(x)
aprox
```
Probabilidad exacta y comparación:
```{r}
exacta <- 1 - (5 / 6)^4
exacta
all.equal(aprox, exacta)
```
# Ejecicio 3
```{r}
nsim <- 1000
a <- 5
b <- 4
U <- runif(nsim)

f <- function(x) {
    ifelse(x >= b,
        a * b^a / (x^(a + 1)),
        0
    )
}

F <- function(x) {
    ifelse(x >= b,
        1 - (b / x)^a,
        0
    )
}

Finv <- function(u) {
    b / (1 - u)^(1 / a)
}

X <- sapply(U, Finv)
hist(X, freq = FALSE, breaks = "FD")
lines(density(X))

ks.test(X, F)
```
# Ejecicio 4

```{r}
f <- function(x) {
    1 / (1 + x^2)
}
```

```{r}
set.seed(1)
nsim <- 1000
X <- runif(nsim)
Y <- f(X)
```
El intervalo de confianza del error al nivel de confianza $1 - \alpha$ con $\alpha = 0.05$ resulta en

$$
    (\overline X_n -z_{\alpha/2} \frac{S_n}{\sqrt{n}}, \overline X_n + z_{\alpha/2} \frac{S_n}{\sqrt{n}})
$$
donde debemos recordar que 
$$ 
    S_n = \dfrac{\sum_{i=1}^n X_i}{\sqrt{n}}
$$

```{r}
estim <- cumsum(Y) / seq_len(nsim)
estim.err <- sqrt(cumsum((Y - estim)^2)) / seq_len(nsim)
plot(estim,
    type = "l",
    xlab = "Número de simulaciones",
    ylab = "Estimación de la integral"
)

z <- qnorm(0.975)
lines(estim - z * estim.err, lty = 3, lwd = 2, col = "blue")
lines(estim + z * estim.err, lty = 3, lwd = 2, col = "blue")

exacto <- pi / 4
abline(h = exacto)

prediccionfinal <- estim[[nsim]]
all.equal(prediccionfinal, exacto)
```
#### Cosa random de ensembles que se me ocurrió para el ejercicio
```{r}
nsimensemble <- 100
numensembles <- nsim / nsimensemble

vprediccionfinalensemble <- vector(mode = "numeric", length = numensembles)
for (i in seq_len(numensembles)) {
    set.seed(i)
    nsim <- nsimensemble
    X <- runif(nsim)
    Y <- f(X)
    estim <- cumsum(Y) / seq_len(nsim)
    vprediccionfinalensemble[[i]] <- estim[[nsim]]
}
prediccionfinalensemble <- mean(vprediccionfinalensemble)
all.equal(prediccionfinalensemble, exacto)
```

